spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e778f1e370420f65551a
            client-secret: ede0f777106c8cdb685c7665edba9356daac4dc9

#spring.security.oauth2.client.registration.github.client-id=3e23a2c6d4dfda3443b4
#spring.security.oauth2.client.registration.github.client-secret=a12a23d213319bbb88bf620ea92569bbb0ccb381

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: DEBUG
